### ISSUE TITLE
Update to comply with CNCF website guidelines

### ISSUE THREAD

**Issue by caniszczyk** [servicemeshinterface/smi-spec.io#10]
https://github.com/cncf/foundation/blob/master/website-guidelines.md

**Comment by lucperkins** [comment]
I'll take this on (once the current "housekeeping" PRs have been merged)

**Comment by bridgetkromhout** [comment]
@lucperkins The housekeeping is done, and this repo is ready for your exciting updates!

**Comment by bridgetkromhout** [comment]
One thing I noticed is the "Open Source from Microsoft Azure" in the footer. In accordance with the guidelines item 2, we'll want to edit that - probably we'd be doing the same as the footer for https://helm.sh with the graphic and CNCF mention?

**Comment by lucperkins** [comment]
@bridgetkromhout Yes, precisely. I'll submit a PR for that soon.

**Comment by bridgetkromhout** [comment]
Hi, @lucperkins! Is there anything else we need to do on this issue to be compliant with the CNCF website guidelines? Thanks!

**Comment by lucperkins** [comment]
@bridgetkromhout Nope! This brings the site into compliance.

Just FYI, it *is* okay per the guidelines to mention that a project originally came from a specific company or organization (or group of orgs in this case). So feel free to add a call-out of that sort if you like.
