### ISSUE TITLE
Site footer tidy-up

### ISSUE THREAD

**Issue by flynnduism** [servicemeshinterface/smi-spec.io#26]
Small tidy up issue  following #24

**Comment by bridgetkromhout** [comment]
Hi @flynnduism - I see an issue in the footer (unsure if it's the same or different) - is there remaining work in progress that will resolve this? Thanks!

![image](https://user-images.githubusercontent.com/2104453/78705830-b2b72100-78d3-11ea-9735-d6b9b1f169e5.png)

**Comment by flynnduism** [comment]
Oh thanks @bridgetkromhout, layout is certainly wonky in webkit browsers. [Fix here for review](https://github.com/servicemeshinterface/smi-spec.io/pull/29).

**Comment by bridgetkromhout** [comment]
Hi, @flynnduism - I think this issue might be resolved? Thanks!
