### ISSUE TITLE
add logo for links on social

### ISSUE THREAD

**Issue by bridgetkromhout** [servicemeshinterface/smi-spec.io#34]
I noticed that tweets linking to this site are using the Hugo default instead of the SMI logo:

https://twitter.com/SMI_spec/status/1248655059627290624

![image](https://user-images.githubusercontent.com/2104453/79135703-6194aa80-7d75-11ea-94d6-c3beb5ace8ee.png)

Maybe adding the logo in the right place in the theme would work?

**Comment by flynnduism** [comment]
👍 

I'll add a [twitter card](https://davidwalsh.name/twitter-cards) to the site header. That will render a preview + logo when shared on social media.

**Comment by bridgetkromhout** [comment]
Thanks!
