### ISSUE TITLE
define process for adding blog posts

### ISSUE THREAD

**Issue by bridgetkromhout** [servicemeshinterface/smi-spec.io#36]
It's exciting to see the work people are doing in this space! In an initial discussion on Cloud Native Slack #smi, we talked about the goal of the blog: to share work happening in the SMI space.

We thought about rules for blog posts:
1) be useful and informative for readers, who won't need to buy specific commercial offerings in order to learn something
2) does not need to exclusively cover open source software, but also should not be primarily product pitches
3) should disclose and link to the employer of the person writing the blog post

Some questions to consider:
1) do we want blog posts to have the usual number of spec reviewers (two)? 
2) do we want to specify these reviewers should be from different employers?

**Comment by bridgetkromhout** [comment]
Pinging @grampelberg @stefanprodan @lachie83 as folks who may have opinions on how we onboard blog posts.

**Comment by bettyjunod** [comment]
RE: questions

Who / how many folks are in the defined spec reviewers group?  

At least different from the submitter :)

**Comment by bridgetkromhout** [comment]
Spec reviewers: https://github.com/servicemeshinterface/smi-spec/blob/master/CODEOWNERS

**Comment by tomkerkhove** [comment]
**Q: Are cross-over posts welcome from other (CNCF) projects?**
For example, we are building an SMI scaler for [KEDA](http://keda.sh/), once that's finished are you open for a post showing how both work together?

No concrete plans yet but just checking.
