### ISSUE TITLE
Blog Post: SMI Conformance

### ISSUE THREAD

**Issue by leecalcote** [servicemeshinterface/smi-spec.io#55]
SMI Conformance tooling has landed and initial results are being published. A blog post explaining this tooling and conformance report is warranted.

**Comment by bridgetkromhout** [comment]
Sounds good. Info about how to add a blog post is here: https://github.com/servicemeshinterface/smi-spec.io#how-to-add-a-blog-post - please let us know if you run into any issues. Thanks.

**Comment by bridgetkromhout** [comment]
https://smi-spec.io/blog/validating-smi-conformance-with-meshery/ is posted
